language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor/bin/simple-phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit
    - SYMFONY_DEPRECATIONS_HELPER=9
    - ACTION="install"

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: SYMFONY="4.4.*"
        ACTION="update"
    - php: 7.4
    - php: 8.0

before_install:
  - '[[ "$TRAVIS_PHP_VERSION" == "7.4snapshot" ]] || phpenv config-rm xdebug.ini'
  - composer self-update
  # Set memory to max (memory fail)
  - '[[ "$ACTION" == "install" ]] || echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini'
  # Set stability to dev to allow 4.4dev and 5.0dev
  - '[[ "$ACTION" == "install" ]] || composer config minimum-stability dev'
  # Change version of symfony when need
  - '[[ "$ACTION" == "install" ]] || composer config extra.symfony.require $SYMFONY'

install:
  - php -r "echo ini_get('memory_limit').PHP_EOL;"
  # install or update
  - composer $ACTION
  - ./vendor/bin/simple-phpunit install

script:
  - ./vendor/bin/simple-phpunit
  # this checks that the source code follows the Symfony Code Syntax rules
  - '[[ "$TRAVIS_PHP_VERSION" == "7.4" ]] || ./vendor/bin/php-cs-fixer fix --diff --dry-run -v'
  #  Fail CI if the repo is in a dirty state after building assets (only for current release ie install)
  #-  if [[ "$ACTION" == "install" ]]; then yarn install && yarn encore production && git add --all && git diff --staged --exit-code; fi
  - composer validate